// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVl-HeBwSiGSkMyGLK2HQn6n3mb0xWxR4',
    appId: '1:329899461322:web:752de7dc5bb8c39d1b0233',
    messagingSenderId: '329899461322',
    projectId: 'fir-task-b3c5f',
    authDomain: 'fir-task-b3c5f.firebaseapp.com',
    storageBucket: 'fir-task-b3c5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDFZY5wqBS1dkeKyMydgx46LaQa3MRi6A',
    appId: '1:329899461322:android:10595a3e1e528a981b0233',
    messagingSenderId: '329899461322',
    projectId: 'fir-task-b3c5f',
    storageBucket: 'fir-task-b3c5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtSToT2PYdpQt4WE26WroBYeMQHc6K_Y8',
    appId: '1:329899461322:ios:f5451665835ae62b1b0233',
    messagingSenderId: '329899461322',
    projectId: 'fir-task-b3c5f',
    storageBucket: 'fir-task-b3c5f.appspot.com',
    iosBundleId: 'com.example.firebaseTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtSToT2PYdpQt4WE26WroBYeMQHc6K_Y8',
    appId: '1:329899461322:ios:f5451665835ae62b1b0233',
    messagingSenderId: '329899461322',
    projectId: 'fir-task-b3c5f',
    storageBucket: 'fir-task-b3c5f.appspot.com',
    iosBundleId: 'com.example.firebaseTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVl-HeBwSiGSkMyGLK2HQn6n3mb0xWxR4',
    appId: '1:329899461322:web:2731b7dc5d14828d1b0233',
    messagingSenderId: '329899461322',
    projectId: 'fir-task-b3c5f',
    authDomain: 'fir-task-b3c5f.firebaseapp.com',
    storageBucket: 'fir-task-b3c5f.appspot.com',
  );
}
